version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER="lisa"
      - MYSQL_DATABASE="clusters_db"
      - MYSQL_PASSWORD="password"
      - MYSQL_ROOT_PASSWORD="password"
    volumes:
      - clusters_vol:/var/lib/mysql/
    ports:
      - 3307:3306
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    depends_on:
      - db

volumes:
  clusters_vol:
