version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_USER: 'dexter'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'drosmokers_test_db'
    volumes:
      - test_vol:/var/lib/mysql/
    ports:
      - "3306:3306"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - test_vol:/var/lib/mysql
    depends_on:
      - web

volumes:
  test_vol:
