# Generated by Django 3.2.4 on 2022-03-31 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('package_date', models.DateField()),
                ('test_date', models.DateField()),
                ('thc_content', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cbd_content', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Terpene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('batch', models.ManyToManyField(to='strains.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strains.strain'),
        ),
    ]
