# Generated by Django 4.0.3 on 2022-03-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('package_date', models.DateField()),
                ('test_date', models.DateField()),
                ('thc_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cbd_content', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Grower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('I', 'Indica'), ('S', 'Sativa'), ('H', 'Hybrid')], max_length=6)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TerpeneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limonene', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pinenee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('caryophillene', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('myrcene', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strains.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='grower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strains.grower'),
        ),
        migrations.AddField(
            model_name='batch',
            name='strain_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strains.strain'),
        ),
        migrations.AddField(
            model_name='batch',
            name='terpenes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strains.terpeneprofile'),
        ),
    ]
