# Generated by Django 4.0.3 on 2022-03-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='strain_fk',
            new_name='strain',
        ),
    ]
