# Generated by Django 4.0.3 on 2022-03-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0002_rename_strain_fk_batch_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='terpeneprofile',
            name='terpinene',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
