# Generated by Django 4.0.3 on 2022-03-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0004_alter_grower_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
