# Generated by Django 3.2.4 on 2022-04-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0006_alter_strain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terpeneprofile',
            old_name='pinenee',
            new_name='pinene',
        ),
    ]
