# Generated by Django 4.0.3 on 2022-04-11 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0009_alter_batch_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terpeneprofile',
            old_name='caryophillene',
            new_name='caryophyllene',
        ),
    ]
