# Generated by Django 4.0.3 on 2022-04-12 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0010_rename_caryophillene_terpeneprofile_caryophyllene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='terpenes',
        ),
        migrations.AddField(
            model_name='terpeneprofile',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strains.batch'),
            preserve_default=False,
        ),
    ]
