# Generated by Django 4.0.3 on 2022-04-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0011_remove_batch_terpenes_terpeneprofile_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='image',
            field=models.ImageField(blank=True, default='default_bud.jpeg', null=True, upload_to='./'),
        ),
    ]
