# Generated by Django 4.0.3 on 2022-04-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0015_alter_batch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='terpeneprofile',
            name='linalool',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='terpeneprofile',
            name='caryophyllene',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='terpeneprofile',
            name='humulene',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='terpeneprofile',
            name='limonene',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='terpeneprofile',
            name='myrcene',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='terpeneprofile',
            name='pinene',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
