# Generated by Django 4.0.3 on 2022-04-25 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0017_alter_rating_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='test_date',
            new_name='final_test_date',
        ),
        migrations.AlterField(
            model_name='strain',
            name='family',
            field=models.CharField(choices=[('In', 'Indica'), ('Sa', 'Sativa'), ('Hy', 'Hybrid')], max_length=6),
        ),
        migrations.AlterField(
            model_name='terpeneprofile',
            name='batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='strains.batch'),
        ),
    ]
